### ISSUE TITLE
[IMTABLES] error running query

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/mine-issues#122]
From @adf-ncgr 

this was generated from applying a filter using the histogram of lengths UI. Apparently it generates floating values and someone else demands they be integers...
```
We encountered an error running a query from an
embedded result table.

page: https://mines.legumeinfo.org/legumemine/report.do?id=169205990
service: https://mines.legumeinfo.org/legumemine/service/
error: Error: XML is well formatted but query contains errors:
Value in constraint GeneFamily.proteins.length >= 327.8 is not in correct format for type of Integer.

date-stamp: Fri Aug 25 2023 22:13:41 GMT-0600 (Mountain Daylight Time)

-------------------------------
IMJS: 3.18.1
-------------------------------
IMTABLES: 2.1.0
-------------------------------
QUERY: <query model="genomic" view="GeneFamily.proteins.primaryIdentifier GeneFamily.proteins.name GeneFamily.proteins.description GeneFamily.proteins.organism.name GeneFamily.proteins.strain.identifier GeneFamily.proteins.length" ><join path="GeneFamily.proteins.organism" style="OUTER"/><join path="GeneFamily.proteins.strain" style="OUTER"/><constraint path="GeneFamily.id" op="=" value="169205990" code="A" /><constraint path="GeneFamily.proteins.length" op="&gt;=" value="327.8" /><constraint path="GeneFamily.proteins.length" op="&lt;=" value="359" /></query>
-------------------------------
STACK: Error: XML is well formatted but query contains errors:
Value in constraint GeneFamily.proteins.length >= 327.8 is not in correct format for type of Integer.

at module.exports.<anonymous> (https://mines.legumeinfo.org/CDN/js/intermine/im-tables/latest/imtables.js:42368:31)
at EventEmitter.emit (https://mines.legumeinfo.org/CDN/js/intermine/im-tables/latest/imtables.js:50494:17)
at Response.handle (https://mines.legumeinfo.org/CDN/js/intermine/im-tables/latest/imtables.js:54570:19)
at xhr.onreadystatechange (https://mines.legumeinfo.org/CDN/js/intermine/im-tables/latest/imtables.js:54333:13)
```

**Comment by sammyjava** [comment]
Where is the histogram of lengths UI?

**Comment by sammyjava** [comment]
> Where is the histogram of lengths UI?

You mean one of the Datatables tools?

**Comment by adf-ncgr** [comment]
Yes, I think so. This 
<img width="292" alt="image" src="https://github.com/legumeinfo/mine-issues/assets/2009605/61ede88c-66be-4089-b522-d69979bb7934">

**Comment by adf-ncgr** [comment]
though I can't seem to reproduce the behavior I only vaguely recall
