### ISSUE TITLE
jointvetchmine not handling gene families correctly

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#42]
for example, a vanilla query for gene families give the following error (something similar happening with keyword searches that should return gene families; also, gene family section in gene report pages blank):

We encountered an error running a query from an
embedded result table.

page: https://mines.legumeinfo.org/jointvetchmine/results.do?trail=%257Cquery%257Cresults.0&queryBuilder=true
service: https://mines.legumeinfo.org/jointvetchmine/service/
error: Error: Service failed. Please contact support.
date-stamp: Thu Aug 19 2021 16:09:30 GMT-0600 (Mountain Daylight Time)

-------------------------------
IMJS: 3.18.1
-------------------------------
IMTABLES: 2.1.0
-------------------------------
QUERY: <query model="genomic" view="GeneFamily.description GeneFamily.identifier" sortOrder="GeneFamily.description ASC" ></query>
-------------------------------
STACK: Error: Service failed. Please contact support.
at module.exports.<anonymous> (https://mines.legumeinfo.org/CDN/js/intermine/im-tables/2.2.0-beta/imtables.js:42368:31)
at module.exports.EventEmitter.emit (https://mines.legumeinfo.org/CDN/js/intermine/im-tables/2.2.0-beta/imtables.js:50494:17)
at module.exports.Response.handle (https://mines.legumeinfo.org/CDN/js/intermine/im-tables/2.2.0-beta/imtables.js:54570:19)
at XMLHttpRequest.xhr.onreadystatechange (https://mines.legumeinfo.org/CDN/js/intermine/im-tables/2.2.0-beta/imtables.js:54333:13)

**Comment by sammyjava** [comment]
I just bumped JointvetchMine to 5.0.8.1 and gene families are fine, etc.
