### ISSUE TITLE
Pg errors storing Newick (legume.genefam.fam1.M65K.trees_ML_rooted) and ProteinDomain (interpro)

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/mine-issues#83]
Mainly a note to self for the moment.

I don't think we need to store the Newick since I'm linking off to a tree viewer elsewhere in the LIS galaxy. I don't know what has changed, these sources loaded fine before. Perhaps some Pg update changed index defaults. Will investigate.

```
<class name="Newick" extends="java.lang.Object" is-interface="false" term="">                                                                                                                                      
        <attribute name="contents" type="java.lang.String"/>                                                                                                                                                       
        <attribute name="identifier" type="java.lang.String"/>                                                                                                                                                     
        <reference name="phylotree" referenced-type="Phylotree"/>                                                                                                                                                  
        <reference name="geneFamily" referenced-type="GeneFamily"/>                                                                                                                                                
</class>
```

```
Caused by: java.sql.SQLException: Error writing to database, running statement COPY Newick (contents, identifier, phylotreeId, geneFamilyId) FROM STDIN BINARY, data size = 319723
        at org.intermine.sql.writebatch.FlushJobPostgresCopyImpl.flush(FlushJobPostgresCopyImpl.java:55)
        at org.intermine.sql.writebatch.Batch$BatchFlusher.run(Batch.java:461)
Caused by: org.postgresql.util.PSQLException: ERROR: index row requires 28408 bytes, maximum size is 8191
```

```
Caused by: java.sql.SQLException: Error writing to database, running statement COPY ProteinDomain (class, description, id, type, name, primaryIdentifier, shortName) FROM STDIN BINARY, data size = 31820734
        at org.intermine.sql.writebatch.FlushJobPostgresCopyImpl.flush(FlushJobPostgresCopyImpl.java:55)
        at org.intermine.sql.writebatch.Batch$BatchFlusher.run(Batch.java:461)
Caused by: org.postgresql.util.PSQLException: ERROR: index row size 3216 exceeds maximum 2712 for index "proteindomain__description_equals"
  Hint: Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
```

**Comment by sammyjava** [comment]
Weird. Blew away the db, created a new one and loaded these two sources fine. No idea.
